import FiniteDependence.Core.Process

/-!
# Basic notions for colorings as stochastic processes

This file defines the basic properties used in Theorem 1 of Holroyd–Liggett,
*Finitely dependent coloring* (arXiv:1403.2448v4):

* proper colorings of `ℤ`;
* stationarity (shift-invariance);
* `k`-dependence via independence of past and future σ-algebras.
-/

namespace FiniteDependence.Coloring

open MeasureTheory ProbabilityTheory

/-- A (proper) `q`-coloring of `ℤ` is an assignment of `q` colors to each integer,
with adjacent integers having different colors. -/
def IsColoring {q : ℕ} (x : ℤ → Fin q) : Prop :=
  ∀ i : ℤ, x i ≠ x (i + 1)

/-- The left shift on colorings of `ℤ`. -/
abbrev shift {q : ℕ} (x : ℤ → Fin q) : ℤ → Fin q :=
  FiniteDependence.shift x

/-- A probability measure on colorings is *stationary* if it is invariant under the left shift. -/
abbrev IsStationary {q : ℕ} (μ : ProbabilityMeasure (ℤ → Fin q)) : Prop :=
  FiniteDependence.IsStationary μ

/-- The σ-algebra generated by the coordinate maps at indices `j < i`. -/
abbrev pastMeasurableSpace {q : ℕ} (i : ℤ) : MeasurableSpace (ℤ → Fin q) :=
  FiniteDependence.pastMeasurableSpace (coord := fun x : ℤ → Fin q => x) i

/-- The σ-algebra generated by the coordinate maps at indices `j ≥ i + k`. -/
abbrev futureMeasurableSpace {q : ℕ} (i : ℤ) (k : ℕ) : MeasurableSpace (ℤ → Fin q) :=
  FiniteDependence.futureMeasurableSpace (coord := fun x : ℤ → Fin q => x) i k

/-- The σ-algebra generated by the coordinate maps at indices in a set `S`. -/
abbrev coordMeasurableSpace {q : ℕ} (S : Set ℤ) : MeasurableSpace (ℤ → Fin q) :=
  FiniteDependence.coordMeasurableSpace (coord := fun x : ℤ → Fin q => x) S

/-- `μ` is `k`-dependent if the past and future (separated by a gap of size `k`) are independent.

This follows the definition in Holroyd–Liggett (arXiv:1403.2448v4): for each `i : ℤ`, the
process on indices `< i` is independent from the process on indices `≥ i + k`. -/
abbrev IsKDependent {q : ℕ} (μ : ProbabilityMeasure (ℤ → Fin q)) (k : ℕ) : Prop :=
  FiniteDependence.IsKDependent (coord := fun x : ℤ → Fin q => x) (μ := (μ : Measure _)) k

/-- Two index sets are `k`-separated if every pair of indices is at distance `> k`. -/
abbrev IndexSeparated (A B : Set ℤ) (k : ℕ) : Prop :=
  FiniteDependence.IndexSeparated A B k

/-- `μ` is `k`-dependent in the noncontiguous sense if any two `k`-separated index sets
generate independent σ-algebras. -/
abbrev IsKDependentNoncontig {q : ℕ} (μ : ProbabilityMeasure (ℤ → Fin q)) (k : ℕ) : Prop :=
  FiniteDependence.IsKDependentNoncontig (coord := fun x : ℤ → Fin q => x) (μ := (μ : Measure _)) k

end FiniteDependence.Coloring
