import FiniteDependence.Core.Process

/-!
# Human-facing definitions

This file contains the minimal predicates used by the public theorem statements in
`FiniteDependence/API/MainTheorems.lean`.
-/

namespace FiniteDependence

open MeasureTheory ProbabilityTheory

/-! ## Stationarity

We use the left shift `FiniteDependence.shift` (defined in `FiniteDependence/Core/Process.lean`) and
its induced notion of stationarity:

`IsStationary μ` means `(μ : Measure (ℤ → α)).map shift = (μ : Measure (ℤ → α))`.
-/

/-! ## Basic combinatorial predicates on configurations -/

/-- A proper `q`-coloring of the integer line: adjacent sites have different colors. -/
def IsColoring {q : ℕ} (c : ℤ → Fin q) : Prop :=
  ∀ i : ℤ, c i ≠ c (i + 1)

/--
A greedy proper `3`-coloring of the integer line.

Colors are `0,1,2` (corresponding to human labels `1,2,3`):
* every color-`1` vertex has a neighboring color `0`,
* every color-`2` vertex has a neighboring color `0` and a neighboring color `1`.
-/
def IsGreedyThreeColoring (c : ℤ → Fin 3) : Prop :=
  IsColoring c ∧
    (∀ i : ℤ, c i = 1 → c (i - 1) = 0 ∨ c (i + 1) = 0) ∧
    (∀ i : ℤ, c i = 2 →
      (c (i - 1) = 0 ∨ c (i + 1) = 0) ∧
        (c (i - 1) = 1 ∨ c (i + 1) = 1))

/-! ### MIS as a shift of finite type

We view a `0/1` configuration `x : ℤ → Fin 2` as an indicator of an independent set.
Maximality is equivalent to forbidding the length-3 word `000`, and independence is equivalent
to forbidding the length-2 word `11`.
-/

/-- No adjacent ones (`11` never occurs). -/
def No11 (x : ℤ → Fin 2) : Prop :=
  ∀ i : ℤ, ¬(x i = 1 ∧ x (i + 1) = 1)

/-- No run of three zeros (`000` never occurs). -/
def No000 (x : ℤ → Fin 2) : Prop :=
  ∀ i : ℤ, ¬(x i = 0 ∧ x (i + 1) = 0 ∧ x (i + 2) = 0)

/-- A maximal independent set configuration on `ℤ`, expressed as forbidden patterns `11` and `000`. -/
def IsMIS (x : ℤ → Fin 2) : Prop :=
  No11 x ∧ No000 x

/-! ### Weak 2-coloring as a shift of finite type

For `q = 2`, the weak coloring constraint on the line is equivalently captured by forbidding
monochromatic length-3 runs (`000` and `111`).
-/

/-- No run of three ones (`111` never occurs). -/
def No111 (x : ℤ → Fin 2) : Prop :=
  ∀ i : ℤ, ¬(x i = 1 ∧ x (i + 1) = 1 ∧ x (i + 2) = 1)

/-- Weak 2-coloring on `ℤ`, expressed as forbidden patterns `000` and `111`. -/
def IsWeakTwoColoring (x : ℤ → Fin 2) : Prop :=
  No000 x ∧ No111 x

/-! ## Two notions of finite dependence (specialized to configurations) -/

/--
Cut-form `k`-dependence for a configuration-valued process.

This is the Holroyd–Liggett definition used throughout the coloring development: for every cut
position `i`, the σ-algebra generated by coordinates `< i` is independent from the σ-algebra
generated by coordinates `≥ i + k`.
-/
def IsKDependentCut {α : Type*} [MeasurableSpace α]
    (μ : ProbabilityMeasure (ℤ → α)) (k : ℕ) : Prop :=
  FiniteDependence.IsKDependent (coord := fun x : ℤ → α => x) (μ := (μ : Measure _)) k

/--
Noncontiguous `k`-dependence for a configuration-valued process.

Any two index sets at pairwise distance `> k` generate independent coordinate σ-algebras.
-/
def IsKDependentNoncontigConfig {α : Type*} [MeasurableSpace α]
    (μ : ProbabilityMeasure (ℤ → α)) (k : ℕ) : Prop :=
  FiniteDependence.IsKDependentNoncontig (coord := fun x : ℤ → α => x) (μ := (μ : Measure _)) k

/-- `μ` is a stationary, `k`-dependent proper `q`-coloring law on `ℤ`. -/
def IsStationaryKDependentColoring (q : ℕ) (k : ℕ) (μ : ProbabilityMeasure (ℤ → Fin q)) : Prop :=
  IsStationary μ ∧
    IsKDependentCut μ k ∧
    (μ : Measure (ℤ → Fin q)) {x | IsColoring x} = 1

/-- Existence of a stationary, `k`-dependent proper `q`-coloring law on `ℤ`. -/
def ExistsStationaryKDependentColoring (q : ℕ) (k : ℕ) : Prop :=
  ∃ μ : ProbabilityMeasure (ℤ → Fin q), IsStationaryKDependentColoring q k μ

/-- `μ` is a stationary, `k`-dependent greedy proper `3`-coloring law on `ℤ`. -/
def IsStationaryKDependentGreedyThreeColoring (k : ℕ)
    (μ : ProbabilityMeasure (ℤ → Fin 3)) : Prop :=
  IsStationary μ ∧
    IsKDependentCut μ k ∧
    (μ : Measure (ℤ → Fin 3)) {x | IsGreedyThreeColoring x} = 1

/-- Existence of a stationary, `k`-dependent greedy proper `3`-coloring law on `ℤ`. -/
def ExistsStationaryKDependentGreedyThreeColoring (k : ℕ) : Prop :=
  ∃ μ : ProbabilityMeasure (ℤ → Fin 3), IsStationaryKDependentGreedyThreeColoring k μ

/--
`μ` is a stationary, `k`-dependent MIS law on `ℤ`.

This bundles:
* stationarity (`IsStationary μ`),
* cut-form `k`-dependence (`IsKDependentCut μ k`),
* almost-sure MIS support (`μ {x | IsMIS x} = 1`).
-/
def IsStationaryKDependentMIS (k : ℕ) (μ : ProbabilityMeasure (ℤ → Fin 2)) : Prop :=
  IsStationary μ ∧
    IsKDependentCut μ k ∧
    (μ : Measure (ℤ → Fin 2)) {x | IsMIS x} = 1

/-- Existence of a stationary, `k`-dependent MIS law on `ℤ`. -/
def ExistsStationaryKDependentMIS (k : ℕ) : Prop :=
  ∃ μ : ProbabilityMeasure (ℤ → Fin 2), IsStationaryKDependentMIS k μ

/--
`μ` is a stationary, `k`-dependent weak-2-coloring law on `ℤ`.

This bundles:
* stationarity (`IsStationary μ`),
* cut-form `k`-dependence (`IsKDependentCut μ k`),
* almost-sure weak-2 support (`μ {x | IsWeakTwoColoring x} = 1`).
-/
def IsStationaryKDependentWeakTwoColoring (k : ℕ) (μ : ProbabilityMeasure (ℤ → Fin 2)) : Prop :=
  IsStationary μ ∧
    IsKDependentCut μ k ∧
    (μ : Measure (ℤ → Fin 2)) {x | IsWeakTwoColoring x} = 1

/-- Existence of a stationary, `k`-dependent weak-2-coloring law on `ℤ`. -/
def ExistsStationaryKDependentWeakTwoColoring (k : ℕ) : Prop :=
  ∃ μ : ProbabilityMeasure (ℤ → Fin 2), IsStationaryKDependentWeakTwoColoring k μ

end FiniteDependence
