import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Probability.Independence.Basic

/-!
# Shared notions for processes on `ℤ`

This module factors out the basic measurable/probabilistic definitions used across the
repository:

* stationarity for processes indexed by `ℤ` (via the left shift on functions `ℤ → α`);
* finite `k`-dependence, both in the Holroyd–Liggett “cut” form and the noncontiguous
  `IndexSeparated` form, phrased in terms of coordinate σ-algebras.

The intent is that both the coloring construction (`FiniteDependence.Coloring`) and the MIS
impossibility proof (`FiniteDependence.MIS`) can share these definitions.
-/

namespace FiniteDependence

open MeasureTheory ProbabilityTheory

/-! ## Coordinate σ-algebras -/

section Coord

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-- The σ-algebra generated by the coordinate maps at indices `j < i`. -/
def pastMeasurableSpace (coord : Ω → ℤ → α) (i : ℤ) : MeasurableSpace Ω :=
  ⨆ j : {j : ℤ // j < i}, MeasurableSpace.comap (fun ω : Ω => coord ω j.1) inferInstance

/-- The σ-algebra generated by the coordinate maps at indices `j ≥ i + k`. -/
def futureMeasurableSpace (coord : Ω → ℤ → α) (i : ℤ) (k : ℕ) : MeasurableSpace Ω :=
  ⨆ j : {j : ℤ // i + k ≤ j}, MeasurableSpace.comap (fun ω : Ω => coord ω j.1) inferInstance

/-- The σ-algebra generated by the coordinate maps at indices in a set `S`. -/
def coordMeasurableSpace (coord : Ω → ℤ → α) (S : Set ℤ) : MeasurableSpace Ω :=
  ⨆ j : {j : ℤ // j ∈ S}, MeasurableSpace.comap (fun ω : Ω => coord ω j.1) inferInstance

end Coord

/-! ## Finite dependence on `ℤ` -/

/-- Two index sets are `k`-separated if every pair of indices is at distance `> k`. -/
def IndexSeparated (A B : Set ℤ) (k : ℕ) : Prop :=
  ∀ ⦃a⦄, a ∈ A → ∀ ⦃b⦄, b ∈ B → Int.natAbs (a - b) > k

section Dependence

variable {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]

/-- `μ` is `k`-dependent (cut form) if the past and future (separated by a gap of size `k`)
are independent for every cut location `i`. -/
def IsKDependent (coord : Ω → ℤ → α) (μ : Measure Ω) (k : ℕ) : Prop :=
  ∀ i : ℤ,
    Indep (pastMeasurableSpace (coord := coord) i) (futureMeasurableSpace (coord := coord) i k) μ

/-- `μ` is `k`-dependent in the noncontiguous sense if any two `k`-separated index sets generate
independent σ-algebras. -/
def IsKDependentNoncontig (coord : Ω → ℤ → α) (μ : Measure Ω) (k : ℕ) : Prop :=
  ∀ ⦃A B : Set ℤ⦄, IndexSeparated A B k →
    Indep (coordMeasurableSpace (coord := coord) A) (coordMeasurableSpace (coord := coord) B) μ

end Dependence

/-! ## Stationarity for function-valued processes -/

/-- The left shift on configurations `ℤ → α`. -/
def shift {α : Type*} (x : ℤ → α) : ℤ → α :=
  fun i => x (i + 1)

/-- Measurability of the left shift on configurations `ℤ → α`. -/
lemma measurable_shift {α : Type*} [MeasurableSpace α] : Measurable (shift (α := α)) := by
  classical
  refine measurable_pi_lambda _ (fun i => ?_)
  simpa [shift, FiniteDependence.shift] using (measurable_pi_apply (a := i + 1))

/-- A probability measure on processes `ℤ → α` is *stationary* if it is invariant under the left
shift. -/
def IsStationary {α : Type*} [MeasurableSpace α] (μ : ProbabilityMeasure (ℤ → α)) : Prop :=
  (μ : Measure (ℤ → α)).map shift = (μ : Measure (ℤ → α))

end FiniteDependence
